Bookstore: add reducers and actions
amejid/bookstore pull request #2
Opened 2022-08-15 09:34 UTC by amejid

## Milestone 2: Add reducers and actions

In this PR, the following were implemented:-

- No linter errors
- Followed the correct Gitflow
- Created redux store and reducers for books and categories

2022-08-15 10:14 UTC, Bondok6 requested changes
## Hi @amejid 🙋‍♂️, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Highlights

- No linter errors ✅
- Your repo is professional ✅
- Professional README file ✅

## Required Changes ♻️
- [ ] Great job adding `MIT.md` file and using the Microverse template 💯, but I noticed you forgot to customize it, So kindly add your name and customize it 👌 

![image](https://user-images.githubusercontent.com/45231276/184617975-57b58a6c-01ea-49cc-be66-9621bdd7135d.png)


- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-15 10:14 UTC, Bondok6 commented on src/redux/books/books.js
> +export default booksSlice.reducer;
- [ ] I can see that you used `createSlice` from `toolkit` to write your book's actions and reducers and this is not wrong, But according to the requirements, you should write your book's actions and reducer using the [ducks pattern](https://github.com/erikras/ducks-modular-redux). So kindly recreate this file using [ducks pattern](https://github.com/erikras/ducks-modular-redux) to follow the requirements 💯👌

> It should be something like

```
// Define Action Type
const ADD = 'bookstore/books/ADD';
const REMOVE = 'bookstore/books/REMOVE';

export default function booksReducer(state = [], action) {
  switch (action.type) {
    case ADD: return ... ;
    case REMOVE: return ... ;
    default: return state;
  }
}

export function addBook(book) { ... }

export function removeBook(id) { ... }
```

![-2](https://user-images.githubusercontent.com/45231276/184617059-a7187888-29c6-4ba1-8d71-447bc33cd965.PNG)

2022-08-15 10:14 UTC, Bondok6 commented on src/redux/categories/categories.js
> +export default categoriesSlice.reducer;
- [ ] The same thing here, Please check the comment above ⬆

2022-08-15 11:01 UTC, amejid commented
Thanks for the feedback, all the issues are addressed in the subsequent commits.

2022-08-15 11:04 UTC, Bondok6 approved these changes
# STATUS: APPROVED :green_circle: :clap: 

## Hi @amejid 🙋‍♂️, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

TO HIGHLIGHT:

- No linter errors ✅
- Great job adding MIT.md file ✅
- Great Job using Use store, actions, and reducers ✅
- Professional README.md file 💯

Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

<img src="https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966" />


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-15 11:06 UTC, merged

2022-10-14 11:18 UTC, amejid commented
Thank you for reviewing and approving my code.